# Generated by Django 5.1.3 on 2024-11-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=0, max_length=11, unique=True),
        ),
        migrations.DeleteModel(
            name='CustomUserAdmin',
        ),
    ]
