## از تصویر پایه استفاده می‌کنیم
#FROM python:3.9
#
## تنظیم دایرکتوری کاری
#WORKDIR /app
#
## نصب وابستگی‌ها
#COPY requirements.txt /app/
#RUN pip install --no-cache-dir -r requirements.txt
#
## کپی کردن کد پروژه
#COPY . /app/
#
## اجرای دستورات مربوط به Django
#CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
