# Generated by Django 5.1.3 on 2024-11-26 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percent', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('category_id', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-discount_percent'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percent', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('product_id', models.CharField(default=True, max_length=40)),
            ],
            options={
                'ordering': ['-discount_percent'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('discount_per_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.categorydiscount')),
            ],
        ),
        migrations.RemoveField(
            model_name='discountcodeuser',
            name='discount',
        ),
        migrations.DeleteModel(
            name='DiscountPerProduct',
        ),
        migrations.DeleteModel(
            name='DiscountCodeUser',
        ),
        migrations.DeleteModel(
            name='DiscountPerCategroyAndUser',
        ),
    ]
